# curl -H "Content-Type: text/plain; charset=UTF-8" -X POST localhost:9999/decrypt -d AQA7AAnsprRSzUu58M7scxiV+7o9mHrBsRXGS+PEPNf0gNyvYkXfA9Prtga9U0iiZRgeZY+DFESBHIYj42EVdxJAkZhoT0M+C6MwjlqZ1tSq/dESB4D3iv9hWpwXbGmDg8jFaWPRKtCxs18SLnQhDvrDbIaPA/gpw5OF9XPOc/VwIypsG4waPLHxEGjbAz4vsHs5+jzecNG5tZnT/eVqTZ3qkv4SI+VSBnDDEow0ivKE2ZdAzCrUeY2ID3OyqYbkodZz0zjJR9syEGcVKzKujsp2RU1S1eUB3JIcswl9R0X8M3OcFXviVCbpVT2Ql+w1E8zIjaL+UjSCFw3jKg+M8SoqGvc1uWPsEORpcYdxNYKIQZAqqLrKh7MktPplMh5zGtg=
POST localhost:9999/decrypt
Content-Type: text/plain; charset=UTF-8

AQA7AAnsprRSzUu58M7scxiV+7o9mHrBsRXGS+PEPNf0gNyvYkXfA9Prtga9U0iiZRgeZY+DFESBHIYj42EVdxJAkZhoT0M+C6MwjlqZ1tSq/dESB4D3iv9hWpwXbGmDg8jFaWPRKtCxs18SLnQhDvrDbIaPA/gpw5OF9XPOc/VwIypsG4waPLHxEGjbAz4vsHs5+jzecNG5tZnT/eVqTZ3qkv4SI+VSBnDDEow0ivKE2ZdAzCrUeY2ID3OyqYbkodZz0zjJR9syEGcVKzKujsp2RU1S1eUB3JIcswl9R0X8M3OcFXviVCbpVT2Ql+w1E8zIjaL+UjSCFw3jKg+M8SoqGvc1uWPsEORpcYdxNYKIQZAqqLrKh7MktPplMh5zGtg=

###

