spring:
  kafka:
    consumer:
      bootstrap-servers: foobar-network:19092 # 로컬에서만. 도커에서는 환경변수로.
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    producer:
      bootstrap-servers: foobar-network:19092 # 로컬에서만. 도커에서는 환경변수로.
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual