spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://mysql-user-service:3306/orders?serverTimezone=UTC&characterEncoding=UTF-8
    url: ${COMPOSE_SPRING_DATASOURCE_URL}
    username: root
    password: test1357