services:
  foobar-mysql:
    image: mysql:5.7.39-debian
    restart: always
    #    command: --lower_case_table_names=1
    container_name: foobar-mysql
    hostname: foobar-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=test1357
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=test1357
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    networks:
      - foobar-network
  eda-sample-discovery-service:
    image: chagchagchag/eda-sample-discovery-service
    container_name: eda-sample-discovery-service
    ports:
      - "8761:8761"
    networks:
      - foobar-network
  eda-sample-config-service:
    image: chagchagchag/eda-sample-config-service
    container_name: eda-sample-config-service
    ports:
      - "9999:9999"
    networks:
      - foobar-network
  eda-sample-api-gateway:
    image: chagchagchag/eda-sample-api-gateway
    container_name: eda-sample-api-gateway
    environment:
#      spring.config.import: http://eda-sample-config-service:9999
      spring.cloud.config.uri: http://eda-sample-config-service:9999
      eureka.client.serviceUrl.defaultZone: http://eda-sample-discovery-service:8761/eureka/
    ports:
      - "8000:8000"
    networks:
      - foobar-network
  foobar-user-container:
    image: chagchagchag/foobar-user-container
    environment:
      spring.cloud.config.uri: http://eda-sample-config-service:9999
      # spring.rabbitmq.host: rabbitmq
      # spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://eda-sample-discovery-service:8761/eureka/
      logging.file: /api-logs/users-ws.log
      SPRING_DATASOURCE_URL: jdbc:mysql://foobar-mysql:3306/users?serverTimezone=UTC&characterEncoding=UTF-8
      COMPOSE_SPRING_DATASOURCE_URL: jdbc:mysql://foobar-mysql:3306/users?serverTimezone=UTC&characterEncoding=UTF-8
      COMPOSE_SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
      COMPOSE_SPRING_PROFILES_ACTIVE: compose
      SPRING_PROFILES_ACTIVE: compose
    networks:
      - foobar-network
  foobar-order-container:
    image: chagchagchag/foobar-order-container
    environment:
      spring.cloud.config.uri: http://eda-sample-config-service:9999
      # spring.rabbitmq.host: rabbitmq
      # spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://eda-sample-discovery-service:8761/eureka/
      logging.file: /api-logs/users-ws.log
      SPRING_DATASOURCE_URL: jdbc:mysql://foobar-mysql:3306/orders?serverTimezone=UTC&characterEncoding=UTF-8
      COMPOSE_SPRING_DATASOURCE_URL: jdbc:mysql://foobar-mysql:3306/orders?serverTimezone=UTC&characterEncoding=UTF-8
      COMPOSE_SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
      COMPOSE_SPRING_PROFILES_ACTIVE: compose
      SPRING_PROFILES_ACTIVE: compose
    networks:
      - foobar-network
  foobar-display-container:
    image: chagchagchag/foobar-display-container
    environment:
      spring.cloud.config.uri: http://eda-sample-config-service:9999
      # spring.rabbitmq.host: rabbitmq
      # spring.zipkin.base-url: http://zipkin:9411
      eureka.client.serviceUrl.defaultZone: http://eda-sample-discovery-service:8761/eureka/
      logging.file: /api-logs/users-ws.log
      SPRING_DATASOURCE_URL: jdbc:mysql://foobar-mysql:3306/catalogs?serverTimezone=UTC&characterEncoding=UTF-8
      COMPOSE_SPRING_DATASOURCE_URL: jdbc:mysql://foobar-mysql:3306/catalogs?serverTimezone=UTC&characterEncoding=UTF-8
      COMPOSE_SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-broker-1:19092,kafka-broker-2:29092,kafka-broker-3:39092
      COMPOSE_SPRING_PROFILES_ACTIVE: compose
      SPRING_PROFILES_ACTIVE: compose
#      SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS:
    networks:
      - foobar-network