server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: catalog-service
  config:
    import:
      - classpath:local-compose-kafka.yml
      - classpath:local-compose-mysql.yml
      - classpath:custom-kafka-properties.yml
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eda-sample-discovery-service:8761/eureka

logging:
  level:
    net.spring.cloud.prototype.orderservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, httptrace, info, metrics, prometheus
